### ISSUE TITLE
[Question] Can uiKey be determined on mount?

### ISSUE THREAD

**Issue by sompylasar** [tonyhb/redux-ui#1]
This looks necessary to make several stateful components of one type.

**Comment by tonyhb** [comment]
Yeah, good call.  Going to have a think about the API and how to do this nicely.  Will add it today.

**Comment by tonyhb** [comment]
Just pushed a new update which introduces the idea of "scoped context" to UI state. In short:
1. each `@ui` component now gets its own context 
2. nested `@ui` components inherit context from all decorated parents

This means that you can do things like add `@ui()` to a list of components; each component can use _the same_ UI keys and state will not be affected.  You can also still modify the entire browser chrome's UI state from any child component, which is the fundamental idea behind UI state.

Here's the commit message:

---

Add all parent UI contexts to children.  This is UI programming.

Introduce the concept of scoping to UI state. This is exactly the same
as block-level scoping in programming:
- each UI decorator introduces a new 'scope' which inherits all variables
  from parent scopes.
- UI variables defined in child contexts take precedence over parent
  contexts
- all UI state variables must be defined in a decorator to be used

Given a nested set of components A => B => C (such that A is the parent, B is
A's child and C is B's child) we now organize UI as follows:

``` js
// A gets its own context with the default UI state below.
// `this.props.ui` will contain this state map.
@ui({
  state: {
    filter: '',
    isFormVisible: true,
    isBackgroundRed: false
  }
})
class A extends Component {
  render() {
    return <B />;
  }
}

// B inherits context from A and adds its own context.
// This means that this.props.ui still contains A's state map.
@ui()
class B extends Component {
  render() {
    return <C />;
  }
}

// C inherits context from its parent B. This works recursively,
// therefore C's `this.props.ui` has the state map from `A` **plus**
// `someChildProp`.
//
// Setting variables within C updates within the context of A; all UI
// components connected to this UI key will receive the new props.
@ui({
  state: {
    someChildProp: 'foo'
  }
})
class C extends Component {
  render() {
    return (
      <div>
        <p>I have my own UI state C and inherit UI state from B and A</p>
        <p>If I define variables which collide with B or A mine will
        be used, as it is the most specific context.</p>
    );
  }
}
```

**Comment by sompylasar** [comment]
:+1: except the comment is unclear:

```
// Setting variables within C updates within the context of A; all UI
// components connected to this UI key will receive the new props.
```

and conflicts with

```
        <p>If I define variables which collide with B or A mine will
        be used, as it is the most specific context.</p>
```

If I set a variable `someChildProp` within C, will it propagate `someChildProp` into A's scope?

**Comment by tonyhb** [comment]
@sompylasar For now, no, it won't propagate into A's scope just because of how React's contexts works.

It's hard for us to watch 'down' the tree for changes.  If a parent mounds a child and the child sets context the parents are generally unaware of this.

Is this something you're looking for?

**Comment by sompylasar** [comment]
> For now, no, it won't propagate into A's scope just because of how React's contexts works.

Thanks! I think the comments should be updated to reflect this.

> Is this something you're looking for?

That was just a question for clarification, I was just wondering because I didn't get it from the comments.

> It's hard for us to watch 'down' the tree for changes. If a parent mounds a child and the child sets 
> context the parents are generally unaware of this.

If the child calls `updateUI`, this function could notify the parents under the hood.

**Comment by tonyhb** [comment]
Sweet, thanks for the info!

Want to keep this as close to block-scoping as possible so I'm wary of adding child variables to a parent's context.  Procedurally, the variables in nested scopes are only visible to that scope and down.  If we look at that as a component tree they'll be visible to components in which state is defined and all of their children... not their parents.

If this comes up will have a think and apply your solution :)

**Comment by sompylasar** [comment]
I didn't mean to add variables from children to parents. I meant if parent
defines a variable, and a child alters its value, will the parent see the
change?

**Comment by tonyhb** [comment]
Yeah, the parent will see the change and so will any of its other child views that use the UI decorator

**Comment by sompylasar** [comment]
:+1: thanks! I've tried to use the module but stumbled upon an issue #8, please have a look.

**Comment by tonyhb** [comment]
:+1: thanks for reporting, looking to fix by tomorow
