### ISSUE TITLE
Using a non-decorator syntax

### ISSUE THREAD

**Issue by thomasdavis** [tonyhb/redux-ui#12]
Currently using this in a hybrid es6 and coffeescript app where everything is slowly being ported to es6/babel. Unfortunately I need to use redux-ui on some of the coffeescript files, any tips on how I should approach this?

**Comment by thomasdavis** [comment]
For anyone needing this, in Coffeescript I've seemingly got it working by 

```
ui = require 'redux-ui'
SideMenuClass = React.createClass {
  blah: () ->
    ...
RealSideMenuClass = ui.default({initialThing: 1})(SideMenuClass)
```

**Comment by tonyhb** [comment]
Thanks for adding this to our issues.  We'll keep this open until we add this to the readme :)

**Comment by tonyhb** [comment]
Added documentation in 0ad02891994140db19c3b14b274410aaec6a2310 - thanks!
