### ISSUE TITLE
compatibility with redux-immutablejs

### ISSUE THREAD

**Issue by keit** [tonyhb/redux-ui#13]
Hi, I am using the combineReducers from redux-immutablejs, which always passes immutablejs object as state whereas redux-ui is expecting plain javascript object. I made a patch to make it work with redux-immutablejs and wondering if you are interested in.

**Comment by tonyhb** [comment]
Yes please! Open up a PR and we'll review and accept. Thanks!

**Comment by keit** [comment]
Cool. I just hard-coded so once I conditionalised I will send PR.

**Comment by tonyhb** [comment]
:+1: thanks very much

**Comment by KidkArolis** [comment]
Running into the same issue

**Comment by KidkArolis** [comment]
Or maybe not, I'm actually using `redux-immutable` not `redux-immutablejs`, hm..

**Comment by KidkArolis** [comment]
Yeah, had to replace 3 `state.ui` references with `state.get('ui')`, sounds like that could be configurable somehow.

**Comment by tonyhb** [comment]
Should be fixed in master :)

**Comment by tonyhb** [comment]
The reference commit is 0cc47ac
