### ISSUE TITLE
how to set UI state from outside the component

### ISSUE THREAD

**Issue by pke** [tonyhb/redux-ui#17]
I have user assist redux-saga that updates a `hint` property. I don't see a public action of redux-ui, which I could use to update that hint.

**Comment by maxmantz** [comment]
EDIT: It is possible to register reducers now, see issue #4

**Comment by tonyhb** [comment]
You can calculate default state by passing in a function, and if you need to respond to actions you should use custom reducers as @maxmantz says in issue #4.

Please re-open with an example of what you need to do if this doesn't solve your problem.
