### ISSUE TITLE
How to use it with an already connected component

### ISSUE THREAD

**Issue by pke** [tonyhb/redux-ui#19]
I can't use the decorator way so I have to use the HOC approach.
I wonder if the store listeners get duplicated if I do:

`export default connect(state => state.account)(ui()(Login))`

Or whats the correct way to do that?

Using a decorator gives me:

`Invariant Violation: Could not find "store" in either the context or props of "Connect(UI)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(UI)".`

```
@ui("login")
class Login {
}
export default connect(state => state.account, { login, loginSuccess })(Login)
```

I'd have hoped the component does not directly connect to the store but instead uses the default redux way to communicate with the store?

**Comment by tonyhb** [comment]
To solve: it seems as tough you don't have a `<Provider>` as a root component which provides the store context. This allows all child components to fetch the store to load state. 

---

The UI component uses `connect` from `react-redux` to connect to the store and load UI state. It also connects to the store directly to access state to work around a timing issue when merging UI props from parent state.
