### ISSUE TITLE
'Uncaught TypeError: state.get is not a function' after adding the reducer

### ISSUE THREAD

**Issue by teeli** [tonyhb/redux-ui#24]
I added the ui reducer as the last reducer in my combineReducers function, but I an error `Uncaught TypeError: state.get is not a function` which points to [line 97 in action-reducer.js](https://github.com/tonyhb/redux-ui/blob/master/src/action-reducer.js#L97)

Any ideas why this is not working?

My `reducers/index.js`:

```
import { combineReducers } from 'redux';
import { reducer as uiReducer } from 'redux-ui';
import session from './session';
import users from './users';

export default combineReducers({
  session,
  users,
  ui: uiReducer
});
```

**Comment by tonyhb** [comment]
Thanks for the heads up. It seems as though somehow the UI state tree is being nuked. 

Some questions:
1. Can you breakpoint in action-reducer and paste the value of `state` here (and `typeof` state).
2. Do you have any custom reducers within your UI component (#4)? If so make sure these return state.
3. If not, is something else potentially breaking the UI state tree?

**Comment by teeli** [comment]
> Can you breakpoint in action-reducer and paste the value of state here (and typeof state).

It appears to be an `object` that contains only an empty `__reducers` object.

> Do you have any custom reducers within your UI component (#4)? If so make sure these return state.

No, the app doesn't actually even use any components that would use redux-ui on initial page load. It's using react-router to navigate to those components. I'm not using any redux router component though (unlike in #4). Could it cause issues if the navigation state is not stored in redux?

> If not, is something else potentially breaking the UI state tree?

Any ideas what it could be? I know my custom reducers at least don't have anything to do with UI state.

Shooting in the dark, one thing that comes to my mind is that it's an isomorphic app, where the initial view is rendered serverside (so it's also using redux and react in serverside).

**Comment by teeli** [comment]
I finally figured out what my issue was. The first view of my app is rendered on the server and the resulting redux state is passed to the client as JSON, where it is set as the initial state of the redux store. That initial state JSON also contains JSON.stringified version of the redux-ui's ui state and that's what causing the problem. Just doing `delete initialState.ui` before passing the data to the client seems to fix the error. This is only a partial solution since I didn't have time (yet) to test how it affects the components using redux-ui.

**Comment by teeli** [comment]
Actually, now that I finally got back to working on this, it's better to delete initialState.ui in the client, right before creating the store with initial state, otherwise server rendering doesn't work. I guess even better would be to generate the UI state from the initial state ui object, but I couldn't quite figure that out yet, so this is a good enough solution for now.

**Comment by tonyhb** [comment]
+t @teeli thanks for finding the root cause. I'd really like to add proper server-side rendering to Redux-UI for 1.0 or 1.1.

This is going to involve proper inflation and deflation of the UI reducer's state, which seems as if was breaking for now.

I'll let you know when it's ready by replying to this thread (if I remember!).  If not, check out the changelog when we hit 1.0 and 1.1.

Thanks again!
