### ISSUE TITLE
Sending state across scenes?

### ISSUE THREAD

**Issue by jshthornton** [tonyhb/redux-ui#28]
Let's say we have two scenes A and B.

When user clicks a button on A they are taken to B with certain UI state already in effect.
In A you could perform updateUI with the key of B, but then defaults are not set when mounting B.

Let's also presume that using routing is out of scope.

What would be the recommended method?

**Comment by tonyhb** [comment]
Good question @jshthornton.

The idea here is that changing a button on A updates _user's preferences_ which control UI state.  It might be helpful to think of it like this:

```
  preferences
 /           \
A             B
```

Clicking A updates `state.prefences.thisOptionOnB`, and B defines its initial UI state using the function pattern:

```
@ui({
  state: {
    // use the filter query parma via redux-router as the default
    optionForB: (props, state) => state.preferences.thisOptionOnB
  }
})
```

You could then take the extra step of saving these preferences in local storage or your database.

**Comment by jshthornton** [comment]
+1 good answer.
