### ISSUE TITLE
Expose uiPath

### ISSUE THREAD

**Issue by jshthornton** [tonyhb/redux-ui#32]
If people are using thunks, or sagas then they will need to be able to update the UI from outside of the component. It would be nice to be able to send the uiPath to allow this.

Thoughts?

**Comment by tonyhb** [comment]
Yep, it would be nice to expose the UI path within the component itself. This should probably be a prop so that you can inspect this at runtime too.

Will add this to 0.0.15 — it's fairly easy to do.

Thanks!
