### ISSUE TITLE
Connect with `options` parameter

### ISSUE THREAD

**Issue by irisSchaffer** [tonyhb/redux-ui#33]
`connect` usually has a fourth parameter with options, one of which being `withRef`, which allows to access the wrapped component and thus methods on it.
I find myself in need of accessing a component's methods, but as I wrapped it with UI state, I can't figure out a way of doing so.

From my perspective, I would expect to be able to pass in another parameter to `ui()` with options passed on to the `connect` call. What do you think?

**Comment by tonyhb** [comment]
@irisSchaffer +1 on being able to pass options into the connect call. I'll add this to the roadmap for 0.0.15 — now work has calmed down we should hit this by tomorrow.

Thanks for the feature request!

**Comment by tonyhb** [comment]
Fixed in #38 — the milestone has one more remaining feature before being released
