### ISSUE TITLE
there is no any reason move internal state of a component to a store!

### ISSUE THREAD

**Issue by budarin** [tonyhb/redux-ui#34]
It's a big mistake to move any state of every component to a store!
It's absolutely unnecessary and show completely misunderstanding of flux/redux pattern

**Comment by tonyhb** [comment]
Thanks for your thoughts.  Even if you use this within your app you _don't need to use it for every component_. It's perfectly fine to have local state.  If you're not a fan you don't have to use this.

After working with Redux for a long time on a couple projects at Docker I've found that managing UI state via a reducer is way better in a lot of scenarios, and way less complex for me to set up. Mainly, it's easier composing an app made of several components that modify UI state within redux-ui than doing things locally.
