### ISSUE TITLE
How to preserve ui state after remount.

### ISSUE THREAD

**Issue by ryerh** [tonyhb/redux-ui#59]
Is there any options to let me preserve components' ui state? In some senerio, that component may remount to component tree.

Any thing like this ?

``` javascript
@ui({
  preserveOnUnmount: true,
  state: {
    foo: 'foo',
    bar: 'bar',
  }
})
class BazComponent extends React.Comopnent {}
```

**Comment by zxqx** [comment]
@ryerh Have you tried `persist: true`?

> optional `persist`, defaults to `false`. if set to `true` `persist` will keep UI state for this component after it unmounts. if set to `false` the UI state will be deleted and recreated when the component remounts.

**Comment by ryerh** [comment]
@zakangelle I haven't notice that, thanks 👍
