### ISSUE TITLE
Last version is published by yarn

### ISSUE THREAD

**Issue by matkrzy** [tonyhb/redux-ui#72]
During installation or updating we get:
`error An unexpected error occurred: "https://registry.yarnpkg.com/redux-ui/-/redux-ui-0.1.0.tgz: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?".
`
it should be published by npm

**Comment by tonyhb** [comment]
Thanks, rolling out 0.1.1 :)

**Comment by tonyhb** [comment]
Fixed.  Expected yarn to publish okay... thanks!
