### ISSUE TITLE
Setting up library do we need to initialize ui prop?

### ISSUE THREAD

**Issue by ArcInteractive** [tonyhb/redux-ui#81]
Hi,

I'm a relative newbie to React so maybe I'm just doing something stupid but when trying to integrate this library I get the following error.

```
Warning: Failed prop type: The prop `ui` is marked as required in `UI`, but its value is `undefined`.
    in UI (created by Connect(UI))
    in Connect(UI)
    in Provider
```

Thanks,
Donavan

**Comment by tonyhb** [comment]
Can you post the code you're using which gives this error?

**Comment by ArcInteractive** [comment]
Mmmm, not really, I've settled on just plain Redux for UI state. Thought maybe it was something simple and obvious. I'll try this library again on my next project.

Thanks :-)

**Comment by tonyhb** [comment]
Sounds good :D
